config/routes.rb
Rails.application.routes.draw do
  resources :articles

  devise_for :users, :controllers => { :registrations => "registrations" }

  get 'index',                          to: 'static_pages#index'
  get 'about_the_firm',                 to: 'static_pages#about_the_firm'
  get 'partners',                       to: 'static_pages#partners'
  get 'our_services',                   to: 'static_pages#our_services'
  get 'industries',                     to: 'static_pages#industries'
  get 'careers',                        to: 'static_pages#careers'
  get 'knowledge_base',                 to: 'articles#index', as: 'knowledge_base'
  # get 'contact_us',                     to: 'static_pages#contact_us'

  get 'doug_beach',                     to: 'static_pages#doug_beach'
  get 'gary_freeman',                   to: 'static_pages#gary_freeman'
  get 'gene_lim',                       to: 'static_pages#gene_lim'
  get 'steve_cleland',                  to: 'static_pages#steve_cleland'
  get 'susan_lewis',                    to: 'static_pages#susan_lewis'

  get 'accounting_and_assurance',       to: 'static_pages#accounting_and_assurance', as: 'accounting_assurance'
  get 'business_advisory',              to: 'static_pages#business_advisory'
  get 'complex_business_transaction',   to: 'static_pages#complex_business_transaction'
  get 'cost_segregation',               to: 'static_pages#cost_segregation'
  get 'estate_planning',                to: 'static_pages#estate_planning'
  get 'fraud_prevention',               to: 'static_pages#fraud_prevention'
  get 'mergers',                        to: 'static_pages#mergers'
  get 'starting_a_business',            to: 'static_pages#starting_a_business'
  get 'strategic_planning',             to: 'static_pages#strategic_planning'
  get 'succession',                     to: 'static_pages#succession'
  get 'tax_services',                   to: 'static_pages#tax_services'

  get 'construction',                   to: 'static_pages#construction'
  get 'craft_brewing',                  to: 'static_pages#craft_brewing'
  get 'family_owned_businesses',        to: 'static_pages#family_owned_businesses'
  get 'franchise',                      to: 'static_pages#franchise'
  get 'healthcare',                     to: 'static_pages#healthcare'
  get 'high_net_worth_individuals',     to: 'static_pages#high_net_worth_individuals', as: 'high_net_worth'
  get 'law_firms',                      to: 'static_pages#law_firms'
  get 'manufacturing_and_distribution', to: 'static_pages#manufacturing_and_distribution', as: 'manufacturing_distribution'
  get 'not_for_profit',                 to: 'static_pages#not_for_profit'
  get 'real_estate',                    to: 'static_pages#real_estate'
  get 'retail',                         to: 'static_pages#retail'
  get 'service_firms',                  to: 'static_pages#service_firms'
  get 'technology',                     to: 'static_pages#technology'

  get 'why_bflc',                       to: 'static_pages#why_bflc'
  get 'available_positions',            to: 'static_pages#available_positions'

  get 'contact_us',                     to: 'messages#new', as: 'new_message'
  post 'contact_us',                    to: 'messages#create', as: 'create_message'

  root 'static_pages#index'
end

app/models/message.rb
class Message
  include ActiveModel::Model
  attr_accessor :name, :email, :body
  validates :name, presence: true
  validates :email, presence: true
  validates :body, presence: true
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)

    if @message.valid?
      MessageMailer.contact_us(@message).deliver_now
      flash[:notice] = 'Email has been sent'
      redirect_to root_path
    else
      flash.now[:notice] = 'Please try again'
      render :new
    end
  end

  private
    def message_params
      params.require(:message).permit(:name, :email, :body)
    end
end

app/views/messages/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="map-responsive">
        <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d26484.02300600382!2d-118.385239!3d33.928192!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x80c2b6b65b813807%3A0x294688815e6b5792!2s861+Parkview+Dr+N%2C+El+Segundo%2C+CA+90245!5e0!3m2!1sen!2sus!4v1496669809297" width="600" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
      </div>
    </div>
  </div>

  <hr>

  <div class="row">
    <div class="col-md-4">
      <h4>We are located at:</h4>
      <p class='text-muted'>861 Parkview Drive North, Suite 200</p>
      <p class='text-muted'>El Segundo, CA 90245</p>
      <hr>
      <p class='text-muted'><h5>Tel:</h5> <%= link_to "310-447-1234", 'tel:1-310-447-1234' %></p>
      <p class='text-muted'><h5>Fax:</h5> 310-447-0287</p>

      <p class='text-muted'><h5>email:</h5> <%= link_to "ContactUs@bflc.com", 'mailto:contactus@bflc.com?Subject=Email from BFLC website contact us page' %></p>
    </div>

    <div class="col-md-7 offset-md-1">
      <p class='text-muted'>Do you have a question, comment, suggestion or news tip to pass along to BFLC? If you have a question or comment, please fill out the short form below.</p>

      <br>

        <%= form_for @message, url: create_message_url do |f| %>
            <%= notice %>
            <%= @message.errors.full_messages.join(', ') %>

          <div class='form-group'>
            <%= f.text_field :name, placeholder: 'name', class: 'form-control' %>
          </div>
          <div class='form-group'>
            <%= f.text_field :email, placeholder: 'email', class: 'form-control' %>
          </div>
          <div class='form-group'>
            <%= f.text_area :body, placeholder: 'message', class: 'form-control', rows: 15 %>
          </div>
          <div class="form-group">
            <%= f.submit 'Send', class: 'btn btn-info btn-block', disabled: true %>
          </div>
        <% end %>
    </div>
  </div>
</div>