config/routes.rb
Rails.application.routes.draw do
  resources :articles

  devise_for :users, :controllers => { :registrations => "registrations" }

  get 'index',                          to: 'static_pages#index'
  get 'about_the_firm',                 to: 'static_pages#about_the_firm'
  get 'partners',                       to: 'static_pages#partners'
  get 'our_services',                   to: 'static_pages#our_services'
  get 'industries',                     to: 'static_pages#industries'
  get 'careers',                        to: 'static_pages#careers'
  get 'knowledge_base',                 to: 'articles#index', as: 'knowledge_base'
  # get 'contact_us',                     to: 'static_pages#contact_us'

  get 'doug_beach',                     to: 'static_pages#doug_beach'
  get 'gary_freeman',                   to: 'static_pages#gary_freeman'
  get 'gene_lim',                       to: 'static_pages#gene_lim'
  get 'steve_cleland',                  to: 'static_pages#steve_cleland'
  get 'susan_lewis',                    to: 'static_pages#susan_lewis'

  get 'accounting_and_assurance',       to: 'static_pages#accounting_and_assurance', as: 'accounting_assurance'
  get 'business_advisory',              to: 'static_pages#business_advisory'
  get 'complex_business_transaction',   to: 'static_pages#complex_business_transaction'
  get 'cost_segregation',               to: 'static_pages#cost_segregation'
  get 'estate_planning',                to: 'static_pages#estate_planning'
  get 'fraud_prevention',               to: 'static_pages#fraud_prevention'
  get 'mergers',                        to: 'static_pages#mergers'
  get 'starting_a_business',            to: 'static_pages#starting_a_business'
  get 'strategic_planning',             to: 'static_pages#strategic_planning'
  get 'succession',                     to: 'static_pages#succession'
  get 'tax_services',                   to: 'static_pages#tax_services'

  get 'construction',                   to: 'static_pages#construction'
  get 'craft_brewing',                  to: 'static_pages#craft_brewing'
  get 'family_owned_businesses',        to: 'static_pages#family_owned_businesses'
  get 'franchise',                      to: 'static_pages#franchise'
  get 'healthcare',                     to: 'static_pages#healthcare'
  get 'high_net_worth_individuals',     to: 'static_pages#high_net_worth_individuals', as: 'high_net_worth'
  get 'law_firms',                      to: 'static_pages#law_firms'
  get 'manufacturing_and_distribution', to: 'static_pages#manufacturing_and_distribution', as: 'manufacturing_distribution'
  get 'not_for_profit',                 to: 'static_pages#not_for_profit'
  get 'real_estate',                    to: 'static_pages#real_estate'
  get 'retail',                         to: 'static_pages#retail'
  get 'service_firms',                  to: 'static_pages#service_firms'
  get 'technology',                     to: 'static_pages#technology'

  get 'why_bflc',                       to: 'static_pages#why_bflc'
  get 'available_positions',            to: 'static_pages#available_positions'

  get 'contact_us',                     to: 'messages#new', as: 'new_message'
  post 'contact_us',                    to: 'messages#create', as: 'create_message'

  root 'static_pages#index'
end

app/views/shared/_nav.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded justify-content-center fixed-top navbar-opacity">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <%= link_to image_tag("BFLC_logo_small"), root_path, class: 'navbar-brand' %>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto justify-content-end">
      <li class="nav-item">
        <%= link_to 'About the Firm', about_the_firm_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Partners', partners_path, class: 'nav-link' %>
      </li>
      <!-- <li class="nav-item dropdown">
        <%= link_to 'Partners', partners_path, class: 'nav-link dropdown-toggle', 'data-toggle': 'dropdown', role: 'button', 'aria-haspopup': 'true', 'aria-expanded': 'false' %>
        <div class="dropdown-menu">
          <%#= link_to 'Doug Beach', doug_beach_path, class: 'dropdown-item' %>
          <%#= link_to 'Gary Freeman', gary_freeman_path, class: 'dropdown-item' %>
          <%#= link_to 'Gene Lim', gene_lim_path, class: 'dropdown-item' %>
          <%#= link_to 'Steve Cleland', steve_cleland_path, class: 'dropdown-item' %>
          <%#= link_to 'Susan Lewis', susan_lewis_path, class: 'dropdown-item' %>
        </div>
      </li> -->

      <li class="nav-item dropdown">
        <%= link_to 'Our Services', partners_path, class: 'nav-link dropdown-toggle', 'data-toggle': 'dropdown', role: 'button', 'aria-haspopup': 'true', 'aria-expanded': 'false' %>
        <div class="dropdown-menu">
          <%= link_to 'Accounting and Assurance', accounting_assurance_path, class: 'dropdown-item' %>
          <%= link_to 'Business Advisory', business_advisory_path, class: 'dropdown-item' %>
          <%= link_to 'Complex Business Transaction', complex_business_transaction_path, class: 'dropdown-item' %>
          <%= link_to 'Cost Segregation', cost_segregation_path, class: 'dropdown-item' %>
          <%= link_to 'Estate Planning', estate_planning_path, class: 'dropdown-item' %>
          <%= link_to 'Fraud Prevention', fraud_prevention_path, class: 'dropdown-item' %>
          <%= link_to 'Mergers', mergers_path, class: 'dropdown-item' %>
          <%= link_to 'Starting a Business', starting_a_business_path, class: 'dropdown-item' %>
          <%= link_to 'Strategic Planning', strategic_planning_path, class: 'dropdown-item' %>
          <%= link_to 'Succession', succession_path, class: 'dropdown-item' %>
          <%= link_to 'Tax Services', tax_services_path, class: 'dropdown-item' %>
        </div>
      </li>

      <li class="nav-item dropdown">
        <%= link_to 'Industries', partners_path, class: 'nav-link dropdown-toggle', 'data-toggle': 'dropdown', role: 'button', 'aria-haspopup': 'true', 'aria-expanded': 'false' %>
        <div class="dropdown-menu">
          <%= link_to 'Construction', construction_path, class: 'dropdown-item' %>
          <%= link_to 'Craft Brewing', craft_brewing_path, class: 'dropdown-item' %>
          <%= link_to 'Family Owned Businesses', family_owned_businesses_path, class: 'dropdown-item' %>
          <%= link_to 'Franchise', franchise_path, class: 'dropdown-item' %>
          <%= link_to 'Healthcare', healthcare_path, class: 'dropdown-item' %>
          <%= link_to 'High Net Worth Individuals', high_net_worth_path, class: 'dropdown-item' %>
          <%= link_to 'Law Firms', law_firms_path, class: 'dropdown-item' %>
          <%= link_to 'Manufacturing and Distribution', manufacturing_distribution_path, class: 'dropdown-item' %>
          <%= link_to 'Not-For-Profit', not_for_profit_path, class: 'dropdown-item' %>
          <%= link_to 'Real Estate', real_estate_path, class: 'dropdown-item' %>
          <%= link_to 'Retail', retail_path, class: 'dropdown-item' %>
          <%= link_to 'Service Firms', service_firms_path, class: 'dropdown-item' %>
          <%= link_to 'Technology', technology_path, class: 'dropdown-item' %>
        </div>
      </li>

      <!-- <li class="nav-item">
        <%#= link_to 'Careers', careers_path, class: 'nav-link' %>
      </li> -->

      <li class="nav-item dropdown">
        <%= link_to 'Careers', careers_path, class: 'nav-link dropdown-toggle', 'data-toggle': 'dropdown', role: 'button', 'aria-haspopup': 'true', 'aria-expanded': 'false' %>
        <div class="dropdown-menu">
          <%= link_to 'Why BFLC', why_bflc_path, class: 'dropdown-item' %>
          <%= link_to 'Available Positions', available_positions_path, class: 'dropdown-item' %>
        </div>
      </li>

      <li class="nav-item">
        <%= link_to 'Knowledge Base', knowledge_base_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to 'Contact Us', new_message_path, class: 'nav-link' %>
      </li>

      <% if current_user %>
        <li class="nav-item dropdown black">
          <%= link_to 'Settings', nil, class: 'nav-link dropdown-toggle', 'data-toggle': 'dropdown', role: 'button', 'aria-haspopup': 'true', 'aria-expanded': 'false' %>
          <div class="dropdown-menu">
            <%= link_to 'Edit', edit_user_registration_path, class: 'dropdown-item' %>
            <div class="dropdown-divider"></div>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'dropdown-item red' %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</nav>